version: "3.8"
services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - "4000:80"
      - "4001:443"
    networks:
       api_net:
          ipv4_address: 172.20.0.2
    volumes:
      - server:/data/ecommerceApi/app-data
  db:
    container_name: db
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "4002:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      db_net:
        ipv4_address: 172.20.1.2
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
        PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
        - "4003:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
        db_net:
            ipv4_address: 172.20.1.3
    restart: unless-stopped
volumes:
    database:
      name: database
    server:
        name: server
    pgadmin:
        name: pgadmin
networks:
    api_net:
      driver: bridge
      ipam:
         driver: default
         config:
           - subnet: 172.20.0.0/24
             gateway: 172.20.0.1
    db_net:
      driver: bridge
      ipam:
        driver: default
        config:
         - subnet: 172.20.1.0/24
           gateway: 172.20.1.1
    