version: '3.8'
services:
  webapi:
    build: .
    ports:
      - "4000:80"
      - "4001:443"
      - "4002:7166"
      - "4003:5086"
    networks:
      - app_net
    depends_on:
      - db
    volumes:
      - app-data:/var/lib/app-data
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5433"
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
        - db_net
volumes:
    db-data:
    app-data:
networks:
  app_net:
    driver: bridge
  db_net:
    driver: bridge
    