version: '3.8'
services:
  webapi:
    container_name: webapi
    build: .
    ports:
      - "4000:80"
      - "4001:443"
    networks:
       api_net:
          ipv4_address: 172.20.0.2
    depends_on:
      - db
    volumes:
      - app-data:/var/lib/temporary/ecommerceApi/app-data
  db:
    container_name: db
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "4002:5432"
    volumes:
      - db-data:/var/lib/temporary/ecommerceApi/db-data
    networks:
      db_net:
        ipv4_address: 172.20.1.2
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
        - "4003:80"
    volumes:
      - db-data:/var/lib/temporary/ecommerceApi/db-data/pgadmin
    networks:
        db_net:
            ipv4_address: 172.20.1.3
volumes:
    db-data:
    app-data:
networks:
    api_net:
      driver: bridge
      ipam:
         driver: default
         config:
           - subnet: 172.20.0.0/24
             gateway: 172.20.0.1
    db_net:
      driver: bridge
      ipam:
        driver: default
        config:
         - subnet: 172.20.1.0/24
           gateway: 172.20.1.1
    