version: '3.8'
services:
  webapi:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
    db-data:
    